-- MySQL Script generated by MySQL Workbench
-- Thu Dec 15 10:56:20 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema babydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `babydb` DEFAULT CHARACTER SET utf8 ;
USE `babydb` ;

-- -----------------------------------------------------
-- Table `babydb`.`structure`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `babydb`.`structure` ;

CREATE TABLE IF NOT EXISTS `babydb`.`structure` (
  `structureId` INT NOT NULL AUTO_INCREMENT,
  `numAgrement` BIGINT NOT NULL,
  `telephone` BIGINT NOT NULL,
  `email` VARCHAR(50) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `adresse` VARCHAR(500) NOT NULL,
  `photoProfil` VARCHAR(300) NULL,
  `photoStructure1` VARCHAR(300) NULL,
  `photoStructure2` VARCHAR(300) NULL,
  `photoStructure3` VARCHAR(300) NULL,
  `description` TEXT NULL,
  `pcsc1` TINYINT NULL,
  `nesting` TINYINT NULL,
  `montessori` TINYINT NULL,
  `handi` TINYINT NULL,
  `jardin` TINYINT NULL,
  `sorties` TINYINT NULL,
  `promenades` TINYINT NULL,
  `eveil` TINYINT NULL,
  `musique` TINYINT NULL,
  `art` TINYINT NULL,
  `bilingue` TINYINT NULL,
  `bibli` TINYINT NULL,
  `transport` TINYINT NULL,
  `albumPhoto` TINYINT NULL,
  `photoConnecte` TINYINT NULL,
  `resaInst` TINYINT NOT NULL,
  `dureeMin` INT NULL,
  `dureeMax` INT NULL,
  `maxPlaces` INT NULL,
  `maxHandi` INT NULL,
  `max18Mois` INT NULL,
  `maxNuit` INT NULL,
  `tarifHeure` FLOAT NULL,
  `tarifHoraireSpec` FLOAT NULL,
  `indemnRepas` FLOAT NULL,
  `dateAgrement` DATE NULL,
  `docPmi` VARCHAR(300) NULL,
  `avisGlobal` FLOAT NULL,
  `avisCom` FLOAT NULL,
  `avisProprete` FLOAT NULL,
  `avisSecurite` FLOAT NULL,
  `avisEveil` FLOAT NULL,
  `avisHoraires` FLOAT NULL,
  PRIMARY KEY (`structureId`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `babydb`.`creche`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `babydb`.`creche` ;

CREATE TABLE IF NOT EXISTS `babydb`.`creche` (
  `crecheId` INT NOT NULL AUTO_INCREMENT,
  `siret` BIGINT NOT NULL,
  `nom` VARCHAR(50) NOT NULL,
  `type` VARCHAR(50) NOT NULL,
  `nbEmployes` INT NOT NULL,
  `financementPaje` TINYINT NOT NULL,
  `tarifAtelier` FLOAT NULL,
  `structureId` INT NULL,
  INDEX `Structure.num_agrement_idx` (`structureId` ASC) VISIBLE,
  PRIMARY KEY (`crecheId`),
  CONSTRAINT `fk_structure_creche`
    FOREIGN KEY (`structureId`)
    REFERENCES `babydb`.`structure` (`structureId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `babydb`.`assMat`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `babydb`.`assMat` ;

CREATE TABLE IF NOT EXISTS `babydb`.`assMat` (
  `assMatId` INT NOT NULL AUTO_INCREMENT,
  `numSecu` BIGINT NOT NULL,
  `numUsage` VARCHAR(45) NULL,
  `nomNaissance` VARCHAR(45) NOT NULL,
  `prenom` VARCHAR(45) NOT NULL,
  `enfants` TINYINT NULL,
  `experience` VARCHAR(45) NULL,
  `animaux` TINYINT NULL,
  `nonFumeur` TINYINT NULL,
  `zeroPollution` TINYINT NULL,
  `repas` TINYINT NULL,
  `hygiene` TINYINT NULL,
  `indemnEntetien` FLOAT NULL,
  `indemnKm` FLOAT NULL,
  `tarifHeureSup` FLOAT NULL,
  `docPmi` VARCHAR(300) NULL,
  `assHabitNom` VARCHAR(45) NULL,
  `assHabitNumero` VARCHAR(45) NULL,
  `assHabitAdresse` VARCHAR(500) NULL,
  `assAutoNom` VARCHAR(45) NULL,
  `assAutoNumero` VARCHAR(45) NULL,
  `assAutoAdresse` VARCHAR(500) NULL,
  `docIdentite` VARCHAR(300) NULL,
  `docVitale` VARCHAR(300) NULL,
  `docJustifDom` VARCHAR(300) NULL,
  `docDiplome` VARCHAR(300) NULL,
  `docRespCivile` VARCHAR(300) NULL,
  `docAssAuto` VARCHAR(300) NULL,
  `structureId` INT NULL,
  INDEX `Num_agrement_idx` (`structureId` ASC) VISIBLE,
  PRIMARY KEY (`assMatId`),
  CONSTRAINT `fk_structure_assmat`
    FOREIGN KEY (`structureId`)
    REFERENCES `babydb`.`structure` (`structureId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `babydb`.`famille`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `babydb`.`famille` ;

CREATE TABLE IF NOT EXISTS `babydb`.`famille` (
  `familleId` INT NOT NULL AUTO_INCREMENT,
  `email` VARCHAR(50) NOT NULL,
  `password` VARCHAR(50) NOT NULL,
  `docAssurParent` VARCHAR(300) NULL,
  `docRib` VARCHAR(300) NULL,
  `docAutoImage` VARCHAR(300) NULL,
  `docDivorce` VARCHAR(300) NULL,
  PRIMARY KEY (`familleId`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `babydb`.`enfant`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `babydb`.`enfant` ;

CREATE TABLE IF NOT EXISTS `babydb`.`enfant` (
  `enfantId` INT NOT NULL AUTO_INCREMENT,
  `nom` VARCHAR(45) NOT NULL,
  `prenom` VARCHAR(45) NOT NULL,
  `dateNaissance` DATE NOT NULL,
  `marcheur` TINYINT NULL,
  `allergies` VARCHAR(500) NULL,
  `docCarnetSante` VARCHAR(300) NULL,
  `docActeNaissance` VARCHAR(300) NULL,
  `medecin` VARCHAR(50) NULL,
  `docCertifMed` VARCHAR(300) NULL,
  `docAutoSoins` VARCHAR(300) NULL,
  `docAutoSortie` VARCHAR(300) NULL,
  `docLivretFamille` VARCHAR(300) NULL,
  `familleId` INT NULL,
  PRIMARY KEY (`enfantId`),
  INDEX `Client_id_idx` (`familleId` ASC) VISIBLE,
  CONSTRAINT `fk_famille_enfant`
    FOREIGN KEY (`familleId`)
    REFERENCES `babydb`.`famille` (`familleId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `babydb`.`parent`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `babydb`.`parent` ;

CREATE TABLE IF NOT EXISTS `babydb`.`parent` (
  `parentId` INT NOT NULL AUTO_INCREMENT,
  `nomNaissance` VARCHAR(50) NOT NULL,
  `nomUsage` VARCHAR(50) NULL,
  `prenom` VARCHAR(45) NOT NULL,
  `profession` VARCHAR(45) NULL,
  `telPortable` BIGINT NULL,
  `emailContact` VARCHAR(50) NULL,
  `docJustifRevenus` VARCHAR(300) NULL,
  `docDeclaRevenus` VARCHAR(300) NULL,
  `docSituationPro` VARCHAR(300) NULL,
  `docJustifDom` VARCHAR(300) NULL,
  `numCaf` BIGINT NULL,
  `numSecu` BIGINT NULL,
  `familleId` INT NULL,
  PRIMARY KEY (`parentId`),
  INDEX `Client_id_idx` (`familleId` ASC) VISIBLE,
  CONSTRAINT `fk_famille_parent`
    FOREIGN KEY (`familleId`)
    REFERENCES `babydb`.`famille` (`familleId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `babydb`.`famille_structure`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `babydb`.`famille_structure` ;

CREATE TABLE IF NOT EXISTS `babydb`.`famille_structure` (
  `familleId` INT NOT NULL,
  `structureId` INT NOT NULL,
  `liked` TINYINT NULL,
  PRIMARY KEY (`familleId`, `structureId`),
  INDEX `fk_Client_has_Structure_Structure1_idx` (`structureId` ASC) INVISIBLE,
  CONSTRAINT `fk_famille_has_structure_famille1`
    FOREIGN KEY (`familleId`)
    REFERENCES `babydb`.`famille` (`familleId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_famille_has_structure_structure1`
    FOREIGN KEY (`structureId`)
    REFERENCES `babydb`.`structure` (`structureId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `babydb`.`horaires`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `babydb`.`horaires` ;

CREATE TABLE IF NOT EXISTS `babydb`.`horaires` (
  `horairesId` INT NOT NULL AUTO_INCREMENT,
  `jourSemaine` VARCHAR(45) NULL,
  `ouvert` TINYINT NULL,
  `heureMin` VARCHAR(5) NULL,
  `heureMax` VARCHAR(5) NULL,
  `structureId` INT NULL,
  PRIMARY KEY (`horairesId`),
  INDEX `StructureIdfk_idx` (`structureId` ASC) VISIBLE,
  CONSTRAINT `fk_structure_horaires`
    FOREIGN KEY (`structureId`)
    REFERENCES `babydb`.`structure` (`structureId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `babydb`.`calendrier`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `babydb`.`calendrier` ;

CREATE TABLE IF NOT EXISTS `babydb`.`calendrier` (
  `calendrierId` INT NOT NULL AUTO_INCREMENT,
  `date` DATE NULL,
  `nbPlaces` TINYINT NULL,
  `structureId` INT NOT NULL,
  PRIMARY KEY (`calendrierId`),
  INDEX `fk_table1_structure1_idx` (`structureId` ASC) VISIBLE,
  CONSTRAINT `fk_table1_structure1`
    FOREIGN KEY (`structureId`)
    REFERENCES `babydb`.`structure` (`structureId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----CRECHE 1----- ---

insert into
    structure (
        numAgrement,
        telephone,
        adresse,
        email,
        password,
        resaInst
    )
values (
        '123456789',
        '0240498051',
        '24 rue du casterneau 44000 nantes',
        'crechebambou@orange.fr',
        'CreBam44',
        '0'
    );

insert into
    creche (
        siret,
        nom,
        type,
        nbEmployes,
        financementPaje,
        tarifAtelier,
        structureId
    )
values (
        '4902904830018',
        'Bambou',
        'crêche associative',
        '12',
        '1',
        '0',
        '1'
    );

update structure
set
    transport = '1',
    albumPhoto = '0',
    photoConnecte = '0'
where structureId = 1;

update structure
set
    description = 'La crèche a ouvert en janvier 2003, elle est située dans le secteur Saint-Donatien. Elle accueille les enfants de 10 semaines à 3 ans selon les besoins des parents et les possibilités d accueil de la crèche (tous les jours, quelques jours, une journée). Selon les disponibilités des périscolaires peuvent être accueillis. Les repas sont confectionnés par une restauration externe, ils sont livrés à la crèche quotidiennement, une diététicienne met à jour les menus.'
where structureId = 1;

update structure
set
    pcsc1 = '1',
    nesting = '0',
    montessori = '0',
    handi = '1',
    jardin = '1',
    sorties = '1',
    promenades = '1',
    eveil = '1',
    musique = '1',
    art = '1',
    bilingue = '0',
    bibli = '0'
where structureId = 1;

update structure
set
    dureeMin = '60',
    dureeMax = '690',
    calendrier = '1',
    nbPlaces = '30',
    maxPlaces = '30',
    maxHandi = '15',
    max18mois = '15',
    maxNuit = '0',
    tarifHeure = '2.5',
    tarifHoraireSpec = '3.1',
    indemnRepas = '5.5',
    avisGlobal = '5',
    avisCom = '5',
    avisProprete = '5',
    avisSecurite = '5',
    avisEveil = '5',
    avisHoraires = '5'
where structureId = 1;

update structure
set
    photoStructure3 = 'https://www.caue-observatoire.fr/wp-content/uploads/2015/12/44_29e37147-5490-4d51-b406-6e182f0c4395_5.jpg'
where structureId = '1';

update structure
set
    photoStructure2 = 'https://www.caue-observatoire.fr/wp-content/uploads/2015/12/44_29e37147-5490-4d51-b406-6e182f0c4395_5.jpg'
where structureId = '1';

update structure
set
    photoStructure1 = 'https://www.caue-observatoire.fr/wp-content/uploads/2015/12/44_29e37147-5490-4d51-b406-6e182f0c4395_2.jpg'
where structureId = '1';

update structure set dateAgrement='2022-12-01' where structureId=1;

update structure
set
    photoProfil = 'https://metropole.nantes.fr/infonantes/association/logo/23043'
where structureId = 1;

-- -----CRECHE 2----- --

insert into
    structure (
        numAgrement,
        telephone,
        adresse,
        email,
        password,
        resaInst
    )
values (
        '145623987',
        '0687905645',
        '37 rue dacoté 44000 nantes',
        'crechetest@orange.fr',
        '1234',
        '0'
    );

insert into
    creche (
        siret,
        nom,
        type,
        nbEmployes,
        financementPaje,
        tarifAtelier,
        structureId
    )
values (
        '4902904830018',
        'Test',
        'grande crêche',
        '52',
        '1',
        '0',
        '2'
    );

update structure
set
    transport = '1',
    albumPhoto = '0',
    photoConnecte = '1'
where structureId = 2;

update structure
set
    description = 'Bonjour, voici une petite présentation'
where structureId = 2;

update structure
set
    pcsc1 = '1',
    nesting = '0',
    montessori = '0',
    handi = '0',
    jardin = '1',
    sorties = '0',
    promenades = '1',
    eveil = '1',
    musique = '1',
    art = '1',
    bilingue = '1',
    bibli = '0'
where structureId = 2;

update structure
set
    dureeMin = '60',
    dureeMax = '690',
    calendrier = '1',
    nbPlaces = '30',
    maxPlaces = '30',
    maxHandi = '15',
    max18mois = '15',
    maxNuit = '0',
    tarifHeure = '8.1',
    tarifHoraireSpec = '12.3',
    indemnRepas = '5.5',
    avisGlobal = '5',
    avisCom = '3.4',
    avisProprete = '4',
    avisSecurite = '2.6',
    avisEveil = '5',
    avisHoraires = '4.5'
where structureId = 2;

update structure
set
    photoStructure3 = 'https://www.caue-observatoire.fr/wp-content/uploads/2015/12/44_29e37147-5490-4d51-b406-6e182f0c4395_5.jpg'
where structureId = 2;

update structure
set
    photoStructure2 = 'https://www.caue-observatoire.fr/wp-content/uploads/2015/12/44_29e37147-5490-4d51-b406-6e182f0c4395_5.jpg'
where structureId = 2;

update structure
set
    photoStructure1 = 'https://www.caue-observatoire.fr/wp-content/uploads/2015/12/44_29e37147-5490-4d51-b406-6e182f0c4395_2.jpg'
where structureId = 2;

update structure set dateAgrement='2022-12-01' where structureId=2;

update structure
set
    photoProfil = 'https://metropole.nantes.fr/infonantes/association/logo/23043'
where structureId = 2;

-- -----Famille1----- --

insert into famille (
        email,
        password
    )
values (
        'kevinDu75@exemple.com',
        '0000'
    );

-- -----Parent1----- --

insert into parent (
        nomNaissance,
        prenom,
        familleId
    )
values (
        'Bernard',
        'Kevin',
        '1'
    );

update parent
set
        nomUsage = "beberd",
        profession = "chomeur",
        telPortable = "0669696969",
        emailContact = "kevinDu75@exemple.com",
        numCaf = "0123456789",
        numSecu = "9876543210"
where parentId = 1;

-- -----Enfant1----- --

insert into enfant (
        nom,
        prenom,
        dateNaissance,
        familleId
    )
values (
        'Bernard',
        'Tiphaine',
        '2021-12-15',
        '1'
    );

update enfant
set
        marcheur = "0",
        allergies = "lactose / arachide",
        medecin = "El doctor de Amigos"
where enfantId = 1;

-- -----RELIER FAMILLE 1 ET CRECHE 1 ----- --

insert into famille_structure (
        familleId,
        structureId,
        liked
    )
values (
        '1',
        '1',
        '1'
    );

-- -----CALENDRIER CRECHE 1 ----- --

insert into calendrier (
        date,
        nbPlaces,
        structureId
    )
values (
        "2022-12-25",
        '-1',
        1
    );

insert into calendrier (
        date,
        nbPlaces,
        structureId
    )
values (
        "2022-12-22",
        '2',
        1
    );

-- -----HORAIRES CRECHE 1 ----- --

insert into horaires (
        jourSemaine,
        ouvert,
        heureMin,
        heureMax,
        structureId
    )
values (
        "lundi",
        1,
        "8:00",
        "18:00",
        1
    );

insert into horaires (
        jourSemaine,
        ouvert,
        heureMin,
        heureMax,
        structureId
    )
values (
        "Mardi",
        1,
        "8:00",
        "19:00",
        1
    );

insert into horaires (
        jourSemaine,
        ouvert,
        heureMin,
        heureMax,
        structureId
    )
values (
        "Mercredi",
        1,
        "8:00",
        "13:00",
        1
    );

insert into horaires (
        jourSemaine,
        ouvert,
        heureMin,
        heureMax,
        structureId
    )
values (
        "Jeudi",
        1,
        "8:00",
        "18:00",
        1
    );

insert into horaires (
        jourSemaine,
        ouvert,
        heureMin,
        heureMax,
        structureId
    )
values (
        "Vendredi",
        1,
        "8:00",
        "19:00",
        1
    );

insert into horaires (
        jourSemaine,
        ouvert,
        heureMin,
        heureMax,
        structureId
    )
values (
        "Samedi",
        1,
        "9:00",
        "17:00",
        1
    );

insert into horaires (
        jourSemaine,
        ouvert,
        heureMin,
        heureMax,
        structureId
    )
values (
        "Dimanche",
        0,
        "14:00",
        "17:00",
        1
    );

-- -----HORAIRES CRECHE 2 ----- --

insert into horaires (
        jourSemaine,
        ouvert,
        heureMin,
        heureMax,
        structureId
    )
values (
        "lundi",
        1,
        "8:00",
        "18:00",
        2
    );

insert into horaires (
        jourSemaine,
        ouvert,
        heureMin,
        heureMax,
        structureId
    )
values (
        "Mardi",
        1,
        "8:00",
        "19:00",
        2
    );

insert into horaires (
        jourSemaine,
        ouvert,
        heureMin,
        heureMax,
        structureId
    )
values (
        "Mercredi",
        0,
        "8:00",
        "13:00",
        2
    );

insert into horaires (
        jourSemaine,
        ouvert,
        heureMin,
        heureMax,
        structureId
    )
values (
        "Jeudi",
        1,
        "8:00",
        "18:00",
        2
    );

insert into horaires (
        jourSemaine,
        ouvert,
        heureMin,
        heureMax,
        structureId
    )
values (
        "Vendredi",
        0,
        "8:00",
        "19:00",
        2
    );

insert into horaires (
        jourSemaine,
        ouvert,
        heureMin,
        heureMax,
        structureId
    )
values (
        "Samedi",
        1,
        "9:00",
        "17:00",
        2
    );

insert into horaires (
        jourSemaine,
        ouvert,
        heureMin,
        heureMax,
        structureId
    )
values (
        "Dimanche",
        0,
        "14:00",
        "17:00",
        2
    );