export const activitiesArray = [
    { id: 'check1', name: 'pcsc1', content: 'Je suis formé aux premiers secours' },
    { id: 'check2', name: 'nesting', content: 'Je suis formé à la méthode nesting' },
    { id: 'check3', name: 'montessori', content: 'Je suis formé à la méthode montessori' },
    { id: 'check4', name: 'handi', content: 'Je peux accueillir des enfants en situation de handicap' },
    { id: 'check5', name: 'jardin', content: "Je dispose d'un jardin" },
    { id: 'check6', name: 'sorties', content: 'Je propose des sorties' },
    { id: 'check7', name: 'promenades', content: 'Je propose des promenades' },
    { id: 'check8', name: 'eveil', content: "Je propose des activités d'éveil" },
    { id: 'check9', name: 'musique', content: 'Je propose des activités musicales' },
    { id: 'check10', name: 'art', content: 'Je propose des activités artistiques' },
    { id: 'check11', name: 'bilingue', content: 'Je propose des activités bilingues' },
    { id: 'check12', name: 'bibli', content: 'Je possède une bibliothèque' },
    { id: 'check13', name: 'transport', content: 'Je peux transporter les enfants' },
    { id: 'check14', name: 'albumPhoto', content: 'Je propose un album photo' },
    { id: 'check15', name: 'photoConnecte', content: 'Je propose des photos connectées' },
]